// Generated by `npm run voices`: seconds each voice clip runs.
export const VOICE_DURATIONS: Readonly<Record<string, number>> = {
  gunman_execute_1: 0.91,
  gunman_spotted_1: 0.56,
  gunman_warn_1: 2.23,
  officer_plead_1: 2,
  officer_plead_2: 2.19,
  officer_plead_3: 2.05,
  officer_thanks_1: 4.22,
  shover_after_1: 3.15,
  shover_spotted_1: 1,
  shover_taunt_1: 1.73,
  shover_taunt_2: 1.85,
  shover_taunt_3: 2.23,
  shover_taunt_4: 2.57,
  shover_taunt_5: 2.31,
};
